# Generated by Django 4.2.14 on 2024-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="senha",
            field=models.CharField(default="asdf", max_length=20),
            preserve_default=False,
        ),
    ]
